
genesis:
  template_folder: "/tmp/hyperledger-fabric-network"
  consensus: "raft"
  channel: "mychannel"
  organisations:
    - organisation: "org1"
      domain_name: "bnc.com"
      orderers:
        - orderer: "orderer0"
          host_name: "orderer0.bnc.com"
          port: 7050
      anchorPeer:
        host_name: "peer0.org1.bnc.com"
        port: 7051
    - organisation: "org2"
      domain_name: "bnc.com"
      orderers:
        - orderer: "orderer1"
          host_name: "orderer1.bnc.com"
          port: 7150
      anchorPeer:
        host_name: "peer0.org2.bnc.com"
        port: 7151
