chaincode:
  template_folder: "/tmp/hyperledger-fabric-network"
  root_path_chaincode: "/tmp/hyperledger-fabric-chaincode"
  path_chaincode: "offers"
  lang_chaincode: "node"
  channel: "mychannel"
  chaincode: "offers"
  version: "1.1"
  endorsementPolicy: "OR ('org1MSP.peer','org2MSP.peer')"
  commit:
    - organisation: "org1"
      domain_name: "bnc.com"
      peers:
        - peer: "peer0"
          host_name: "peer0.org1.bnc.com"
          port: 7051
    - organisation: "org2"
      domain_name: "bnc.com"
      peers:
        - peer: "peer0"
          host_name: "peer0.org2.bnc.com"
          port: 7151

