import {Kms} from '../src/kms';
import {OPERATORS} from '../src/utils';

export function getRandomKms(): Kms {
  return {
      idOperator: OPERATORS.OVX,
      publicKey: 'myPublicKey'
  };
}

export const userCertOvx = '-----BEGIN CERTIFICATE-----' +
'MIICNDCCAdqgAwIBAgIUTzMvshyVpeM3HrBABgG9/4wHYhQwCgYIKoZIzj0EAwIw' +
'azELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh' +
'biBGcmFuY2lzY28xFTATBgNVBAoTDG9yZzEubGNlLmNvbTEYMBYGA1UEAxMPY2Eu' +
'b3JnMS5sY2UuY29tMB4XDTIwMDUyMzE4MzIwMFoXDTIxMDUyMzE4MzcwMFowLzEc' +
'MA0GA1UECxMGY2xpZW50MAsGA1UECxMEb3JnMTEPMA0GA1UEAxMGZHpvbmRhMFkw' +
'EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEYv5NBMztmoPzsPbKhpHuGtTIn60cnaiQ' +
't1E0EzSx11m14NE25q5PP0nwWp426/2i3gthZvc+x0J9gSqoAda5TqOBlzCBlDAO' +
'BgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUw2neBarFI6pp' +
'bFMsjTLV8boFpWswKwYDVR0jBCQwIoAgdcfyPZ7n1ct9X/Cz9RW3bb/diYPExEVp' +
'Vf8Sc1/unRowKAYIKgMEBQYHCAEEHHsiYXR0cnMiOnsib3BlcmF0b3IiOiJvdngi' +
'fX0wCgYIKoZIzj0EAwIDSAAwRQIhAOizFZ/kB82a57yCoqA0hPLWszqcP/+IrCkZ' +
'ibtdetPLAiBJhpG5H2vZgBVwO1wTqQ115W6fR1UaNqG0I+40nU9MTA==' +
'-----END CERTIFICATE-----';

export const userCertRidygo = '-----BEGIN CERTIFICATE-----' +
'MIICNzCCAd6gAwIBAgIULgcRlc6RcfuHOqNXsVwFHXI44/MwCgYIKoZIzj0EAwIw' +
'azELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh' +
'biBGcmFuY2lzY28xFTATBgNVBAoTDG9yZzEubGNlLmNvbTEYMBYGA1UEAxMPY2Eu' +
'b3JnMS5sY2UuY29tMB4XDTIwMDUyMzE4NTEwMFoXDTIxMDUyMzE4NTYwMFowMDEc' +
'MA0GA1UECxMGY2xpZW50MAsGA1UECxMEb3JnMTEQMA4GA1UEAxMHZHpvbmRhMjBZ' +
'MBMGByqGSM49AgEGCCqGSM49AwEHA0IABLvuIENcjAANH/PA6L2S1ChRw8fWGq61' +
'KaboqvEw1R+foznzMvz/shNaTFsJDVPZzwFgcJQYDtwftt8UUJhEI2mjgZowgZcw' +
'DgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFA3NyirK2Yvp' +
'34ZQbPMzMjOyMO/TMCsGA1UdIwQkMCKAIHXH8j2e59XLfV/ws/UVt22/3YmDxMRF' +
'aVX/EnNf7p0aMCsGCCoDBAUGBwgBBB97ImF0dHJzIjp7Im9wZXJhdG9yIjoicmlk' +
'eWdvIn19MAoGCCqGSM49BAMCA0cAMEQCIBoIdnWi1DkfuxH4yqx64idSrhpiwuxE' +
'BO1bg5Dnl36pAiB2Ym/odgJDca5yVPI18DSs8ILfYtIOr56DFFlwUf9PGQ==' +
'-----END CERTIFICATE-----';

export const pkOvx = 'BLNzTCyJVqPBr9BcFcuLZpPa0IBhpEFNsbhWyppGTnvzHmgT7B9CB++d8stLY4zRknJhiId2mTqrxTXtwGJTgaY=';
export const skOvx = '2/9buEFZ1cJae3yuPfRA/OHeaVDXShuvSLVJXrseLJ0=';
export const pkRidygo = 'BMgp99zMeErPMmk+/u1xqRBh7HSsDr158P5PNEopXvYM22xULApkH6aa6Chycv1/WWGsKepP5enVZ8WU2/f/YCY=';
export const skRidygo = 'W+yIyxqBAcByCc7xEGk5RmGUgWAUJ3LzYfLUFb0RmWg=';